In [1]:
import pandas as pd
import numpy as np

In [2]:
from pandas import Series, DataFrame

## Pandas Series

In [3]:
ser = pd.Series([10, -2.4, -3, 4.99])
print(ser)
print(ser.values)
print(ser.index)

0    10.00
1    -2.40
2    -3.00
3     4.99
dtype: float64
[10.   -2.4  -3.    4.99]
RangeIndex(start=0, stop=4, step=1)


In [4]:
ser2 = pd.Series([10, -2.4, -3, 4.99], index=['a', 'b', 'c', 'd'])
print(ser2)
print(ser2.values)
print(ser2.index)
print(ser2['a'])
print(ser2[['d', 'c']])
print(ser2[ser2 > 0])

a    10.00
b    -2.40
c    -3.00
d     4.99
dtype: float64
[10.   -2.4  -3.    4.99]
Index(['a', 'b', 'c', 'd'], dtype='object')
10.0
d    4.99
c   -3.00
dtype: float64
a    10.00
d     4.99
dtype: float64


In [5]:
print(ser2*2)
print(np.exp(ser2))
print('b' in ser2)  # '인덱스 키'가 시리즈 내부에 있는가

a    20.00
b    -4.80
c    -6.00
d     9.98
dtype: float64
a    22026.465795
b        0.090718
c        0.049787
d      146.936423
dtype: float64
True


In [6]:
# Dict 형식을 넣어도됨
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
ser3 = pd.Series(sdata)
ser3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [7]:
states = ['Calfornia', 'Ohio', 'Oregon', 'Texas']
ser4 = pd.Series(ser3, states)  # Series를 받아서 새로 받은 index 순서대로 저장. (없으면 NaN)
print(ser4,'\n')
print(pd.isnull(ser4),'\n')
print(pd.notnull(ser4),'\n')

Calfornia        NaN
Ohio         35000.0
Oregon       16000.0
Texas        71000.0
dtype: float64 

Calfornia     True
Ohio         False
Oregon       False
Texas        False
dtype: bool 

Calfornia    False
Ohio          True
Oregon        True
Texas         True
dtype: bool 



In [8]:
print(ser3+ser4)

Calfornia         NaN
Ohio          70000.0
Oregon        32000.0
Texas        142000.0
Utah              NaN
dtype: float64


In [9]:
ser4.name = 'population'
ser4.index.name = 'state'
print(ser4)

state
Calfornia        NaN
Ohio         35000.0
Oregon       16000.0
Texas        71000.0
Name: population, dtype: float64


## Pandas DataFrame

In [10]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [11]:
frame2 = pd.DataFrame(data,
                      columns=['year', 'state', 'pop'],
                      index=['one', 'two', 'three', 'four', 'five', 'six'])  # 순서지정 가능
frame2

year   state  pop
one    2000    Ohio  1.5
two    2001    Ohio  1.7
three  2002    Ohio  3.6
four   2001  Nevada  2.4
five   2002  Nevada  2.9
six    2003  Nevada  3.2

In [12]:
# col을 기준으로 보는법. .state와 동일. 여기다가 값을 넣으면 새로운 col 생성
print(frame2['state'])
print(frame2.loc['four'])

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object
year       2001
state    Nevada
pop         2.4
Name: four, dtype: object


In [13]:
# 값을 추가할 때 해당하는 인덱스가 없다면 NaN으로 들어간다
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [14]:
# state의 값이 Ohio 여부를 담은 bool 값이 담긴 col
frame2['eastern'] = frame2['state'] == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [15]:
# del 예약어로 col을 날릴 수 있다
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [16]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop, index=[2000, 2001, 2002])
frame3.columns.name = 'State'
frame3.index.name = 'Year'
frame3

State  Nevada  Ohio
Year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [17]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [18]:
# index 객체는 row 와 col에 대한 메타데이터를 저장하는 객체
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
#index 객체. 객체 값 변경 X
print(index)
print(index[1:])

Index(['a', 'b', 'c'], dtype='object')
Index(['b', 'c'], dtype='object')


## reindex

In [19]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
print(obj)
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
print(obj2)
obj3=pd.Series(['blue','purple','yellow'], index=[0,2,4])
obj3 = obj3.reindex(range(6), method='ffill') # ffill 은 이전값으로 매꿈
print(obj3)

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64
a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64
0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object


In [20]:
# row col은 다음과 같이 reindex가 가능하다.
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
print(frame)
frame2 = frame.reindex(['a', 'b', 'c', 'd'], columns=states)
print(frame2)

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
   Calfornia  Ohio  Oregon  Texas
a        NaN   0.0     NaN    1.0
b        NaN   NaN     NaN    NaN
c        NaN   3.0     NaN    4.0
d        NaN   6.0     NaN    7.0


In [21]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
print(frame)

# reindex with loc()
# 정작 새로운 값 추가는 안되더라;
print(frame.loc[['d', 'c', 'a'], ['Texas', 'California', 'Ohio']])

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
   Texas  California  Ohio
d      7           8     6
c      4           5     3
a      1           2     0


## drop method

In [22]:
# 인덱스 값 (row) 넘기면 해당 row (axis = 0) 의 값을 다 삭제
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
print(obj)
new_obj = obj.drop('c')
print(new_obj)
multiDrop_obj = obj.drop(['d', 'a'])
print(multiDrop_obj)

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64
a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64
b    1.0
c    2.0
e    4.0
dtype: float64


In [23]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
print(data, '\n')
print(data.drop(['Colorado', 'Ohio']), '\n')
print(data.drop(['three', 'one'], axis=1), '\n')
# inplace 옵션을 True로 두면 객체반환이 아니라 원본객체를 변경
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15 

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15 

          two  four
Ohio        1     3
Colorado    5     7
Utah        9    11
New York   13    15 



one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

## indexing, select with loc, iloc

In [24]:
print(data.loc[['New York', 'Colorado'], ['three', 'one']])
print(data.loc['Colorado':'New York', 'one':'three'])

          three  one
New York     14   12
Colorado      6    4
          one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14


In [25]:
df1 = pd.DataFrame(np.arange(9.0).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.0).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(df1)
print(df2)
print(df2+df1)  # 둘중 하나라도 없으면 NaN이 되버린다.

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0
          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN


In [26]:
df1 = pd.DataFrame(np.arange(12.0).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.0).reshape((4, 5)),
                   columns=list('abcde'))
print(df1+df2)
print(df1.add(df2,fill_value=0))

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN
      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [27]:
arr = np.arange(12.0).reshape((3,4))
print(arr,'\n')
print(arr[0],'\n')
print(arr-arr[0]) # arr[0]가 브로드캐스트 되어 적용된다.

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] 

[0. 1. 2. 3.] 

[[0. 0. 0. 0.]
 [4. 4. 4. 4.]
 [8. 8. 8. 8.]]


In [28]:
frame = pd.DataFrame(np.arange(12.0).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
print(frame, '\n')
print(series, '\n')
print(frame-series)  # DataFrame도 마찬가지

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0 

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64 

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0


In [29]:
series2= pd.Series(range(3),index=['b','e','f'])
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [30]:
series3 = frame['d']
print(frame, '\n')
print(series3, '\n')
print(frame.sub(series3, axis='index'))

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0 

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64 

          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0


In [31]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(frame, '\n')
print(np.abs(frame), '\n')

               b         d         e
Utah    0.240343 -0.640683 -0.871255
Ohio   -0.557980 -0.944461  0.811626
Texas  -0.549774  0.758922  0.301730
Oregon  0.828429  1.592635  0.426009 

               b         d         e
Utah    0.240343  0.640683  0.871255
Ohio    0.557980  0.944461  0.811626
Texas   0.549774  0.758922  0.301730
Oregon  0.828429  1.592635  0.426009 



In [32]:
f = lambda x : x.max() - x.min()
print(frame.apply(f,axis='columns'))
# axis = 함수가 적용되며 다음으로 나아가는 방향
# axis = 0 or index 이면 함수가 각각의 col에 적용
# axis = 1 or columns 이면 함수가 각각의 row에 적용

Utah      1.111598
Ohio      1.756087
Texas     1.308695
Oregon    1.166627
dtype: float64


In [33]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])
print(frame.apply(f))
print(frame.apply(f,axis='columns'))

            b         d         e
min -0.557980 -0.944461 -0.871255
max  0.828429  1.592635  0.811626
             min       max
Utah   -0.871255  0.240343
Ohio   -0.944461  0.811626
Texas  -0.549774  0.758922
Oregon  0.426009  1.592635


In [34]:
format = lambda x : '%.2f' % x # x를 받아서 포맷팅 해준 뒤 내보낸다.
print(frame,'\n')
print(frame.applymap(format),'\n')
print(frame['e'].map(format),'\n')

               b         d         e
Utah    0.240343 -0.640683 -0.871255
Ohio   -0.557980 -0.944461  0.811626
Texas  -0.549774  0.758922  0.301730
Oregon  0.828429  1.592635  0.426009 

            b      d      e
Utah     0.24  -0.64  -0.87
Ohio    -0.56  -0.94   0.81
Texas   -0.55   0.76   0.30
Oregon   0.83   1.59   0.43 

Utah      -0.87
Ohio       0.81
Texas      0.30
Oregon     0.43
Name: e, dtype: object 



## Sorting & Rank

In [35]:
obj = pd.Series(range(4),index=['d','a','b','c'])
print(obj,'\n')
print(obj.sort_index())

d    0
a    1
b    2
c    3
dtype: int64 

a    1
b    2
c    3
d    0
dtype: int64


In [36]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
# 인덱스를 기준으로 정렬
print(frame,'\n')
print(frame.sort_index(),'\n')
print(frame.sort_index(axis=1),'\n')
print(frame.sort_index(axis=1, ascending=False))

       d  a  b  c
three  0  1  2  3
one    4  5  6  7 

       d  a  b  c
one    4  5  6  7
three  0  1  2  3 

       a  b  c  d
three  1  2  3  0
one    5  6  7  4 

       d  c  b  a
three  0  3  2  1
one    4  7  6  5


In [37]:
# 값을 기준으로 정렬, 단 NaN값은 맨 뒤로
obj = pd.Series([4,np.nan,7,np.nan,-3,2])
print(obj.sort_values())

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64


In [38]:
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
print(frame,'\n')
print(frame.sort_values(by='b'),'\n')
print(frame.sort_values(by=['a','b'])) # a col을 기준으로 먼저 정렬하고 같다면 b 기준 

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1 

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1 

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1


In [39]:
obj = pd.Series([7,-5,7,4,2,0,4])
print(obj,'\n')
print(obj.rank(),'\n') 
print(obj.rank(method='first')) # 같은 수여도 먼저 나타나면 높은 순위

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64 

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64 

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64


In [40]:
frame = pd.DataFrame(
    {'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1], 'c': [-2, 5, 8, -2.5]})
frame = frame.sort_index(axis=1)
print(frame)
frame.rank(axis=1)

   a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5


a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

##  Duplicated Index

In [41]:
obj = pd.Series(range(5),index=['a','a','b','b','c'])
print(obj,'\n')
print(obj.index.is_unique,'\n') #인덱스가 중복되는지 여부
print(obj['a'],'\n') # 중복되는 인덱스가 있다면 시리즈를 반환해준다.
print(obj['c']) # 아니라면 스칼라값 반환

a    0
a    1
b    2
b    3
c    4
dtype: int64 

False 

a    0
a    1
dtype: int64 

4


In [42]:
df = pd.DataFrame(np.random.randn(4,3),index=['a','a','b','b'])
print(df,'\n')
print(df.loc['a']) # DataFrame 또한 중복되는 인덱스가 있다면 series가 아닌 데이터프레임 반환

          0         1         2
a -0.147527  0.704130  0.388092
a -1.241268  1.142509  0.506241
b  0.136095 -0.963990 -0.287743
b -1.746812 -1.011805  0.993957 

          0         1         2
a -0.147527  0.704130  0.388092
a -1.241268  1.142509  0.506241


## Summary Statistics

In [43]:
df = pd.DataFrame([[1.4, np.nan],
                   [7.1, -4.5],
                   [np.nan, np.nan],
                   [0.75, -1.3]], 
                  index=['a', 'b', 'c', 'd'], 
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [44]:
print(df.sum(),'\n')
print(df.sum(axis=1),'\n') # skipna = False 로 두면 한쪽이 NA이면 싹다 NA 
print(df.idxmax(),'\n')
print(df.cumsum())

one    9.25
two   -5.80
dtype: float64 

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64 

one    b
two    d
dtype: object 

    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8


In [45]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [46]:
import pandas_datareader.data as web

In [47]:
all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [48]:
all_data

{'AAPL':                   High         Low        Open       Close       Volume  \
 Date                                                                      
 2017-02-06   32.625000   32.224998   32.282501   32.572498  107383600.0   
 2017-02-07   33.022499   32.612499   32.634998   32.882500  152735200.0   
 2017-02-08   33.055000   32.805000   32.837502   33.009998   92016400.0   
 2017-02-09   33.112499   32.779999   32.912498   33.105000  113399600.0   
 2017-02-10   33.235001   33.012501   33.115002   33.029999   80262000.0   
 ...                ...         ...         ...         ...          ...   
 2022-01-31  175.000000  169.509995  170.160004  174.779999  115541600.0   
 2022-02-01  174.839996  172.309998  174.009995  174.610001   85908800.0   
 2022-02-02  175.880005  173.330002  174.750000  175.839996   84914300.0   
 2022-02-03  176.240005  172.119995  174.479996  172.899994   89418100.0   
 2022-02-04  174.100006  170.679993  171.679993  172.389999   82391400.0   
 
  

In [49]:
price

AAPL         IBM        MSFT         GOOG
Date                                                       
2017-02-06   30.659895  133.669601   59.171074   801.340027
2017-02-07   30.951694  135.645844   58.975834   806.969971
2017-02-08   31.071709  134.964050   58.892159   808.380005
2017-02-09   31.296230  135.760773   59.561596   809.559998
2017-02-10   31.225330  136.886948   59.505798   813.669983
...                ...         ...         ...          ...
2022-01-31  174.779999  133.570007  310.980011  2713.969971
2022-02-01  174.610001  135.529999  308.760010  2757.570068
2022-02-02  175.839996  137.250000  313.459991  2960.729980
2022-02-03  172.899994  137.779999  301.250000  2853.010010
2022-02-04  172.389999  137.149994  305.940002  2860.320068

[1260 rows x 4 columns]

In [50]:
volume

AAPL        IBM        MSFT     GOOG
Date                                                   
2017-02-06  107383600.0  2772737.0  19796400.0  1184500
2017-02-07  152735200.0  4051681.0  20277200.0  1241200
2017-02-08   92016400.0  3047103.0  18096400.0  1155300
2017-02-09  113399600.0  3232872.0  22644400.0   989700
2017-02-10   80262000.0  3065512.0  18170700.0  1135000
...                 ...        ...         ...      ...
2022-01-31  115541600.0  5859000.0  46444500.0  1702800
2022-02-01   85908800.0  6200800.0  40894300.0  2513100
2022-02-02   84914300.0  5357200.0  36636000.0  4487500
2022-02-03   89418100.0  6100800.0  43730000.0  2846500
2022-02-04   82391400.0  4140200.0  35070300.0  2458600

[1260 rows x 4 columns]

In [51]:
returns = price.pct_change()
returns.tail()  # 퍼센트 변화율

AAPL       IBM      MSFT      GOOG
Date                                              
2022-01-31  0.026126 -0.006914  0.008824  0.018073
2022-02-01 -0.000973  0.014674 -0.007139  0.016065
2022-02-02  0.007044  0.012691  0.015222  0.073674
2022-02-03 -0.016720  0.003862 -0.038952 -0.036383
2022-02-04 -0.002950 -0.004573  0.015568  0.002562

In [52]:
print(returns['MSFT'].corr(returns['IBM']))  # 상관관계
print(returns['MSFT'].cov(returns['IBM']))  # 공분산

0.4826478483701948
0.0001408344584180223


In [53]:
# 데이터프레임 전체에 적용시
print(returns.corr(), '\n')
print(returns.cov(), '\n')

          AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.427367  0.741828  0.660926
IBM   0.427367  1.000000  0.482648  0.455988
MSFT  0.741828  0.482648  1.000000  0.779535
GOOG  0.660926  0.455988  0.779535  1.000000 

          AAPL       IBM      MSFT      GOOG
AAPL  0.000372  0.000137  0.000250  0.000220
IBM   0.000137  0.000278  0.000141  0.000131
MSFT  0.000250  0.000141  0.000306  0.000236
GOOG  0.000220  0.000131  0.000236  0.000299 



In [54]:
# corrwith를 이용하여 다른 Series와 DataFrame과의 상관관계 계산
print(returns.corrwith(returns.IBM), '\n')

# DataFrame을 넘겨주면 동일한 col에 대한 상관관계 계산
print(returns.corrwith(volume))

AAPL    0.427367
IBM     1.000000
MSFT    0.482648
GOOG    0.455988
dtype: float64 

AAPL   -0.083651
IBM    -0.128699
MSFT   -0.069439
GOOG   -0.095338
dtype: float64


## Managing Data

### CSV

In [55]:
df = pd.read_csv('examples/ex1.csv',sep=",")
df

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [56]:
# header = None이면 첫 row가 col 이름이 되지 않는다 (첫 row는 날라감)
df2 = pd.read_csv('examples/ex2.csv',sep=",", header=None)
df2

0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [57]:
names = ['a','b','c','d','message']
# names로 col의 이름을 지정해줄 수 있고
df2 = pd.read_csv('examples/ex2.csv',sep=",", names=names)
df2

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [58]:
# index_col로 인덱스가 될 col을 설정해줄 수 있다.
df2 = pd.read_csv('examples/ex2.csv',sep=",", names=names, index_col='message')
df2

a   b   c   d
message               
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [59]:
# 계층적 index를 사용하고 싶다면 index_col을 리스트로 넘긴다
parsed = pd.read_csv('examples/csv_mindex.csv', index_col = ['key1','key2'])
parsed

value1  value2
key1 key2                
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [60]:
list(open('examples/ex3.csv'))

['            A         B         C\n',
 'aaa -0.264438 -1.026059 -0.619500\n',
 'bbb  0.927272  0.302904 -0.032399\n',
 'ccc -0.264273 -0.386314 -0.217601\n',
 'ddd -0.871858 -0.348382  1.100491']

In [61]:
#정규 표현식으로 처리하면 간단 \s+
# \s 는 화이트 스페이스를 의미하고 +는 앞에 있는 패턴이 하나 이상 나타남을 의미
result = pd.read_table('examples/ex3.csv',sep='\s+')
result

A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [62]:
list(open('examples/ex4.csv'))

['# hey!\n',
 'a,b,c,d,message\n',
 '# just wanted to make things more difficult for you\n',
 '# who reads CSV files with computers, anyway?\n',
 '1,2,3,4,hello\n',
 '5,6,7,8,world\n',
 '9,10,11,12,foo']

In [63]:
pd.read_csv('examples/ex4.csv',skiprows=[0,2,3]) # skiprows로 건너뛸 row 설정

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [64]:
!type examples\ex5.csv #누락된 값인 NA가 존재한다.

something,a,b,c,d,message


examples\ex5.csv


지정된 파일을 찾을 수 없습니다.
다음 내용 진행 중 오류 발생: #누락된.
지정된 파일을 찾을 수 없습니다.
다음 내용 진행 중 오류 발생: 값인.
지정된 파일을 찾을 수 없습니다.
다음 내용 진행 중 오류 발생: NA가.
지정된 파일을 찾을 수 없습니다.
다음 내용 진행 중 오류 발생: 존재한다..



one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo


In [65]:
result = pd.read_csv('examples/ex5.csv')
print(result)
# na_values => NaN value를 식별할 수 있는 값
sentinels = {'message': ['foo', 'NA'], 'something': ['two']}
result = pd.read_csv('examples/ex5.csv', na_values=sentinels)
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo


something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

In [66]:
pd.options.display.max_rows = 10  # 앞으로 최댄 10개 데이터만 출력
result = pd.read_csv('examples/ex6.csv')
result  # 위에서 5개 밑에서 5개

one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [67]:
pd.read_csv('examples/ex6.csv',nrows=5) # nrows로 처음부터 몇 줄 읽을지 설정

one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [68]:
chunker = pd.read_csv('examples/ex6.csv', chunksize=1000)
print(chunker)  # TextParser 객체가 반환되고 chunksize에 따라 분리된 파일들을 순회 가능
tot = pd.Series([])
for piece in chunker:
    tot = tot.add(piece['key'].value_counts(), fill_value=0)
tot = tot.sort_values(ascending=False)
tot[:10]

C:\Users\Hesh\AppData\Local\Temp/ipykernel_6396/3410942540.py:3: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  tot = pd.Series([])


E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64

In [69]:
asdf = pd.Series([])
asdf=asdf.add(result['key'].value_counts(),fill_value=0)
asdf[:10]

C:\Users\Hesh\AppData\Local\Temp/ipykernel_6396/2984877581.py:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  asdf = pd.Series([])


E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64

In [70]:
data = pd.read_csv('examples/ex5.csv')
print(data)
#to_csv를 이용하여 쉼표 (,) 로 구분된 파일을 생성가능
data.to_csv('examples/out.csv')
! type examples\out.csv

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo
,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo


In [71]:
import sys
#다른 구분자도 가능하고 누락값을 대체 가능
data.to_csv(sys.stdout, sep='|', na_rep='비어있는 칸')

|something|a|b|c|d|message
0|one|1|2|3.0|4|비어있는 칸
1|two|5|6|비어있는 칸|8|world
2|three|9|10|11.0|12|foo


In [72]:
# 원래있던 index와 헤더를 날리거나 맘대로 설정 됨
# colums 는 이름 재지정이 아니라 넣을 columns를 정하는것
print(data.to_csv(sys.stdout, index=False, header=False, na_rep='빵꾸'), '\n')
data.to_csv(sys.stdout, index=False, columns=['a', 'b', 'c','message'], na_rep='빵꾸')

one,1,2,3.0,4,빵꾸
two,5,6,빵꾸,8,world
three,9,10,11.0,12,foo
None 

a,b,c,message
1,2,3.0,빵꾸
5,6,빵꾸,world
9,10,11.0,foo


In [73]:
# 구분자가 한글자면 csv 모듈로 처리가능
import csv
f = open('examples/ex7.csv')
reader = csv.reader(f)
for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']


In [74]:
# zip(*values)로 unzip 해주면 row col을 전치가능
# col에 있는 값들을 순서대로 zip으로 끄집어내주니까
with open('examples/ex7.csv') as f:
    lines = list(csv.reader(f))
header, values = lines[0],lines[1:]
print(header,'\n',values)
data_dict={h:v for h,v in zip(header,zip(*values))}
data_dict

['a', 'b', 'c'] 
 [['1', '2', '3'], ['1', '2', '3']]


{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [75]:
class my_dialect(csv.Dialect):
    lineterminator = '\n' # 파일저장 시 이용할 개행문자 (기본값: '\r\n')
    delimiter = ',' # 필드를 구분하기 위한 문자 (기본값: ',')
    quotechar = '"' # 각 필드에서 값을 둘러싸고 있는 문자 (기본값: ' " ')
    quoting = csv.QUOTE_MINIMAL # 언제 quotechar를 기록기가 생성하고 판독기가 인식해야 하는지를 제어

f = open('examples/ex7.csv')
!type examples\ex7.csv
reader = csv.reader(f, dialect=my_dialect)
for lines in reader:
    print(lines)

"a","b","c"
"1","2","3"
"1","2","3"
['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']


### JSON

In [76]:
import json

In [77]:
!type examples\example.json

[{"a": 1, "b": 2, "c": 3},
 {"a": 4, "b": 5, "c": 6},
 {"a": 7, "b": 8, "c": 9}]


In [78]:
# 이용법 자체는 간단
data = pd.read_json('examples/example.json')
data

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [79]:
print(data.to_json())

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}


### XML and HTML

In [80]:
# HTML 내부에 있는 모든 table 형식의 데이터를 파싱 시도
tables = pd.read_html('examples/fdic_failed_bank_list.html')
print(len(tables))
print(type(tables))  # 각각 데이터프레임 형태로 리스트 객체에 저장
failures = tables[0]
failures.head()

1
<class 'list'>


Bank Name             City  ST   CERT  \
0                   Allied Bank         Mulberry  AR     91   
1  The Woodbury Banking Company         Woodbury  GA  11297   
2        First CornerStone Bank  King of Prussia  PA  35312   
3            Trust Company Bank          Memphis  TN   9956   
4    North Milwaukee State Bank        Milwaukee  WI  20364   

                 Acquiring Institution        Closing Date       Updated Date  
0                         Today's Bank  September 23, 2016  November 17, 2016  
1                          United Bank     August 19, 2016  November 17, 2016  
2  First-Citizens Bank & Trust Company         May 6, 2016  September 6, 2016  
3           The Bank of Fayette County      April 29, 2016  September 6, 2016  
4  First-Citizens Bank & Trust Company      March 11, 2016      June 16, 2016

In [81]:
close_timestamps = pd.to_datetime(failures['Closing Date'])  # 시계열 데이터로 변환
print(close_timestamps, '\n')
print(close_timestamps.dt.year.value_counts())  # 년도 count (09,10년도는 리만사태)

0     2016-09-23
1     2016-08-19
2     2016-05-06
3     2016-04-29
4     2016-03-11
         ...    
542   2001-07-27
543   2001-05-03
544   2001-02-02
545   2000-12-14
546   2000-10-13
Name: Closing Date, Length: 547, dtype: datetime64[ns] 

2010    157
2009    140
2011     92
2012     51
2008     25
       ... 
2004      4
2001      4
2007      3
2003      3
2000      2
Name: Closing Date, Length: 15, dtype: int64


In [82]:
from lxml import objectify

path = 'datasets/mta_perf/Performance_MNR.xml'
parsed = objectify.parse(open(path))
root = parsed.getroot()

In [83]:
data = []

skip_fields = ['PARENT_SEQ', 'INDICATOR_SEQ',
               'DESIRED_CHANGE', 'DECIMAL_PLACES']
for elt in root.INDICATOR:
    el_data = {}
    for child in elt.getchildren():
        if child.tag in skip_fields:
            continue
        el_data[child.tag] = child.pyval  # tag에 달린 value 값 == pyval
    data.append(el_data)

In [84]:
perf =pd.DataFrame(data)
perf.head()

AGENCY_NAME                        INDICATOR_NAME  \
0  Metro-North Railroad  On-Time Performance (West of Hudson)   
1  Metro-North Railroad  On-Time Performance (West of Hudson)   
2  Metro-North Railroad  On-Time Performance (West of Hudson)   
3  Metro-North Railroad  On-Time Performance (West of Hudson)   
4  Metro-North Railroad  On-Time Performance (West of Hudson)   

                                         DESCRIPTION  PERIOD_YEAR  \
0  Percent of commuter trains that arrive at thei...         2008   
1  Percent of commuter trains that arrive at thei...         2008   
2  Percent of commuter trains that arrive at thei...         2008   
3  Percent of commuter trains that arrive at thei...         2008   
4  Percent of commuter trains that arrive at thei...         2008   

   PERIOD_MONTH            CATEGORY FREQUENCY INDICATOR_UNIT YTD_TARGET  \
0             1  Service Indicators         M              %       95.0   
1             2  Service Indicators         M              %       95.0   
2             3  Service Indicators         M              %       95.0   
3             4  Service Indicators         M              %       95.0   
4             5  Service Indicators         M              %       95.0   

  YTD_ACTUAL MONTHLY_TARGET MONTHLY_ACTUAL  
0       96.9           95.0           96.9  
1       96.0           95.0           95.0  
2       96.3           95.0           96.9  
3       96.8           95.0           98.3  
4       96.6           95.0           95.8

In [85]:
# 각각의 태그에 대한 메타데이터를 들고오는 방법
from io import StringIO
tag = '<a href="https://www.google.com">Google</a>'
root = objectify.parse(StringIO(tag)).getroot()

print(root)
print(root.get('href'))  # href값 들고오기
print(root.text)  # 해당 태그의 text값

Google
https://www.google.com
Google


### Binary Data

In [86]:
# 파이썬에 내장된 pickle 직렬화를 이용하면 손쉽게 데이터를 이진 형식으로 저장 가능
# 데이터를 하나의 줄로 정렬해서 이진형식으로 저장했다가 다시 꺼내는것이 가능
# 단 오래 보관할 필요가 없는 경우에 한해서만 저장하자. 괜히 라이브러리 업뎃되면 못꺼낼수도 있다.
frame = pd.read_csv('examples/ex1.csv')
frame

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [87]:
frame.to_pickle('examples/frame_pickle')
pd.read_pickle('examples/frame_pickle')

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [88]:
# HDF5 형식
frame = pd.DataFrame({'a': np.random.randn(100)})
store = pd.HDFStore('mydata.h5','r+') # default가 r이라서 r+해야 w까지 가능
store['obj1'] = frame
store['obj1_col'] = frame['a']
print(store['obj1_col']) # Series

0    -1.168268
1    -0.063975
2    -0.535616
3    -0.152767
4    -3.060779
        ...   
95    0.557715
96   -0.246708
97   -0.190807
98   -0.426644
99    2.529339
Name: a, Length: 100, dtype: float64


In [89]:
# table 저장 스키마를 이용하면 느리지만 쿼리 연산이 편하다.
store.put('obj2', frame, format='table')
store.select('obj2', where=['index>= 10 and index<=15'])
store.close()

In [90]:
frame.to_hdf('mydata.h5','obj3',format='table')
pd.read_hdf('mydata.h5','obj3',where=['index<5'])

a
0 -1.168268
1 -0.063975
2 -0.535616
3 -0.152767
4 -3.060779

### Excel File

In [91]:
xlsx = pd.ExcelFile('examples/ex1.xlsx')
frame = pd.read_excel(xlsx,'Sheet1')
print(frame.columns)
frame=frame.drop('Unnamed: 0',axis=1)
frame

Index(['Unnamed: 0', 'a', 'b', 'c', 'd', 'message'], dtype='object')


a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [92]:
writer = pd.ExcelWriter('examples/ex2.xlsx')
frame.to_excel(writer,'Sheet1')
writer.save()

### Web API

In [93]:
# 판다스 깃허브에서 최근 30개의 이슈 가져오기
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
print(type(resp)) # 반환객체는 requests 객체

<class 'requests.models.Response'>


In [94]:
data = resp.json() # .json 메서드는 json 내용을 파이썬 dict 형태로 변환해줌
data[0]

{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45833',
 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45833/labels{/name}',
 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45833/comments',
 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/45833/events',
 'html_url': 'https://github.com/pandas-dev/pandas/issues/45833',
 'id': 1124854756,
 'node_id': 'I_kwDOAA0YD85DC-vk',
 'number': 45833,
 'title': "BUG: ModuleNotFoundError: No module named 'pandas' (Problem with Python3.9)",
 'user': {'login': 'Nafees-060',
  'id': 63704191,
  'node_id': 'MDQ6VXNlcjYzNzA0MTkx',
  'avatar_url': 'https://avatars.githubusercontent.com/u/63704191?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/Nafees-060',
  'html_url': 'https://github.com/Nafees-060',
  'followers_url': 'https://api.github.com/users/Nafees-060/followers',
  'following_url

In [95]:
issues = pd.DataFrame(data, columns=['number','title','labels','state','created_at'])
issues

number                                              title  \
0    45833  BUG: ModuleNotFoundError: No module named 'pan...   
1    45832        TST: Don't use autouse fixture in test_eval   
2    45831       TST: Don't use autouse fixture in test_stata   
3    45830                        DEPS: unpin numpydoc #39688   
4    45825              BUG: infer_dtype fails on PeriodIndex   
..     ...                                                ...   
25   45795           DEP: Protect some ExcelWriter attributes   
26   45790  BUG: `df.to_hdf` fails when `DatetimeIndex` ha...   
27   45789  BUG: Date time slicing fails for `freq=pd.Date...   
28   45787  BUG: loc raising uncontrolled error when more ...   
29   45785  Regression: Loc raising when indexing mi with ...   

                                               labels state  \
0   [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open   
1   [{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open   
2   [{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open   
3   [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open   
4   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open   
..                                                ...   ...   
25  [{'id': 49254273, 'node_id': 'MDU6TGFiZWw0OTI1...  open   
26  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open   
27  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open   
28  [{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyM...  open   
29  [{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyM...  open   

              created_at  
0   2022-02-05T06:56:26Z  
1   2022-02-05T01:34:47Z  
2   2022-02-05T01:00:24Z  
3   2022-02-04T22:29:49Z  
4   2022-02-04T17:55:45Z  
..                   ...  
25  2022-02-03T03:39:54Z  
26  2022-02-03T00:21:56Z  
27  2022-02-03T00:19:23Z  
28  2022-02-02T23:14:44Z  
29  2022-02-02T21:51:56Z  

[30 rows x 5 columns]

### DataBase

In [96]:
import sqlite3

In [97]:
query ="""
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20),
c REAL, d INTEGER
);"""
con = sqlite3.connect('mydata.sqlite')

con.execute(query)
con.commit()

OperationalError: table test already exists

In [100]:
data = [('Atlanta', 'Georgia', 1.25, 6),
        ('Tallahassee', 'Florida', 2.6, 3),
        ('Sacramento', 'California', 1.7, 5)]
stmt = "INSERT INTO test VALUES(?,?,?,?)"
con.executemany(stmt,data)
con.commit()

In [101]:
cursor = con.execute('select * from test') # SQL 쿼리문하고 동일!
#cursor 객체는 쿼리의 결과를 들고 있다.
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [103]:
# result set 의 columns을 들고옴
print(cursor.description,'\n')

pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

(('a', None, None, None, None, None, None), ('b', None, None, None, None, None, None), ('c', None, None, None, None, None, None), ('d', None, None, None, None, None, None)) 



a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [105]:
#SQL알케미의 read_sql을 이용하여 SQL DB간의 차이를 무시하고 쉽게 데이터를 읽을 수 있음
import sqlalchemy as sqla
db = sqla.create_engine('sqlite:///mydata.sqlite')
pd.read_sql('select* from test',db)

a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5